export const TOOL_LOGO_EXT: Record<string, 'png' | 'svg'> = {
  chatgpt: 'png',
  claude: 'png',
  gemini: 'png',
  perplexity: 'png',
  miro: 'png',
  notion: 'png',
  midjourney: 'png',
  'stable-diffusion': 'png',
  meshy: 'png',
  luma: 'png',
  runway: 'png',
  pika: 'png',
  'adobe-substance': 'png',
  kaedim: 'png',
  polycam: 'png',
  leonardo: 'png',
  embergen: 'png',
  tripo: 'png',
  tooncrafter: 'png',
  seaart: 'png',
  'texture-lab': 'png',
  genie3: 'png',
  layerai: 'png',
  golopix: 'png',
  banana: 'png',
  cursor: 'png',
  copilot: 'png',
  tabnine: 'png',
  'amazon-codewhisperer': 'png',
  elevenlabs: 'png',
  suno: 'png',
  playht: 'png',
  soundraw: 'png',
  'unity-mcp': 'png',
  bezi: 'png',
  coplay: 'png',
  'leonardo-unity': 'png',
  amara: 'png',
  flockbay: 'png',
  ludus: 'png',
  'godot-copilot': 'png',
  fuku: 'png',
  'cocos-copilot': 'png',
  codely: 'png',
  deepseek: 'png',
  qwen: 'png',
  glm: 'png',
  hunyuan: 'png',
  kimi: 'png',
  llama: 'png',
  minimax: 'png',
  grok: 'png',
  wenxin: 'png',
};

function baseUrlPrefix() {
  const base = String(import.meta.env.BASE_URL ?? '/');
  return base.endsWith('/') ? base : `${base}/`;
}

export function toolLogoUrl(id: string): string {
  const ext = TOOL_LOGO_EXT[id] ?? 'png';
  return `${baseUrlPrefix()}tool-logos/${id}.${ext}`;
}

export function toolLogoFallbackUrl(): string {
  return `${baseUrlPrefix()}tool-logos/_placeholder.svg`;
}

export const TOOL_IDS: string[] = [
  'chatgpt',
  'claude',
  'gemini',
  'perplexity',
  'miro',
  'notion',
  'midjourney',
  'stable-diffusion',
  'meshy',
  'luma',
  'runway',
  'pika',
  'adobe-substance',
  'kaedim',
  'polycam',
  'leonardo',
  'embergen',
  'tripo',
  'tooncrafter',
  'seaart',
  'texture-lab',
  'genie3',
  'layerai',
  'golopix',
  'banana',
  'cursor',
  'copilot',
  'tabnine',
  'amazon-codewhisperer',
  'elevenlabs',
  'suno',
  'playht',
  'soundraw',
  'unity-mcp',
  'bezi',
  'coplay',
  'leonardo-unity',
  'amara',
  'flockbay',
  'ludus',
  'godot-copilot',
  'fuku',
  'cocos-copilot',
  'codely',
  'deepseek',
  'qwen',
  'glm',
  'hunyuan',
  'kimi',
  'llama',
  'minimax',
  'grok',
  'wenxin',
];
